import { Marked, type Tokens } from "marked";
import type { DocPage } from "./reference.js";

const STYLE = `
:root { --bg:#ffffff; --fg:#1f2328; --muted:#59636e; --border:#d1d9e0; --code:#f6f8fa; --link:#0969da; --accent:#8250df; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --bg:#0d1117; --fg:#e6edf3; --muted:#9198a1; --border:#3d444d; --code:#151b23; --link:#4493f8; --accent:#ab7df8; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg); font:16px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif; }
main { max-width: 980px; margin: 0 auto; padding: 24px 16px 64px; }
a { color: var(--link); text-decoration: none; } a:hover { text-decoration: underline; }
h1,h2,h3,h4 { line-height:1.25; margin: 1.6em 0 .6em; } h1 { margin-top: .4em; }
h3, h4 { padding-top: .4em; border-top: 1px solid var(--border); }
code { font: 13.5px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; background: var(--code); padding: .1em .35em; border-radius: 6px; }
pre { background: var(--code); padding: 12px 14px; border-radius: 8px; overflow-x: auto; }
pre code { background: none; padding: 0; }
table { border-collapse: collapse; width: 100%; display: block; overflow-x: auto; margin: 0 0 1em; }
th, td { border: 1px solid var(--border); padding: 6px 10px; text-align: left; vertical-align: top; }
th { background: var(--code); }
blockquote { margin: 0 0 1em; padding: 0 1em; color: var(--muted); border-left: 4px solid var(--accent); }
footer { color: var(--muted); font-size: 13px; margin-top: 48px; }
`;

function escapeHtml(s: string): string {
  return s.replace(
    /[&<>"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] ?? c,
  );
}

/** Rewrites `x.md#a` links to `x.html#a` so the HTML tree is self-contained. */
function createMarked(): Marked {
  return new Marked({
    gfm: true,
    walkTokens(token) {
      if (token.type === "link") {
        const t = token as Tokens.Link;
        t.href = t.href.replace(/\.md(#|$)/, ".html$1");
      }
    },
    renderer: {
      code({ text, lang }: Tokens.Code) {
        if (lang === "mermaid") return `<pre class="mermaid">${escapeHtml(text)}</pre>\n`;
        return `<pre><code>${escapeHtml(text)}</code></pre>\n`;
      },
    },
  });
}

export function pageToHtml(page: DocPage, marked: Marked = createMarked()): string {
  const body = marked.parse(page.markdown, { async: false });
  const hasMermaid = page.markdown.includes("```mermaid");
  // Mermaid renders diagrams in the browser. Without network the source stays readable as text.
  const mermaid = hasMermaid
    ? `<script type="module">import m from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs"; m.initialize({ startOnLoad: true, theme: matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "default" });</script>`
    : "";
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(page.title)} · Grasp</title>
<style>${STYLE}</style>
</head>
<body>
<main>
${body}
<footer>Generated by Grasp from static analysis. Every fact cites the file and line it came from.</footer>
</main>
${mermaid}
</body>
</html>
`;
}

export function pagesToHtml(pages: DocPage[]): DocPage[] {
  const marked = createMarked();
  return pages.map((p) => ({
    ...p,
    path: p.path.replace(/\.md$/, ".html"),
    markdown: pageToHtml(p, marked),
  }));
}
