import type { FileRole } from "./types.js";
import { isProgrammingLanguage } from "./languages.js";

/**
 * Files whose contents Grasp never reads, regardless of config.
 * Why: Grasp output can later be sent to an LLM, so secrets must not enter the fact base at all.
 */
const SECRET_PATTERNS: RegExp[] = [
  /(^|\/)\.env(\.[^/]*)?$/,
  /\.(pem|key|p12|pfx|jks|keystore|ppk|asc|gpg)$/i,
  /(^|\/)id_(rsa|dsa|ecdsa|ed25519)(\.pub)?$/,
  /(^|\/)\.(netrc|npmrc|pypirc|htpasswd)$/,
  /(^|\/)credentials(\.json)?$/i,
  /(^|\/)secrets?\.(json|ya?ml|toml)$/i,
];

/** Template files document variable names without values, so they are safe and useful. */
const SECRET_EXCEPTIONS = /(^|\/)\.env\.(example|sample|template|dist|defaults)$/;

export function isSecretPath(path: string): boolean {
  if (SECRET_EXCEPTIONS.test(path)) return false;
  return SECRET_PATTERNS.some((re) => re.test(path));
}

/** Directories skipped even when not gitignored (common in tarballs and non-git checkouts). */
export const DEFAULT_IGNORED_DIRS = [
  ".git",
  "node_modules",
  ".grasp",
  "bower_components",
  ".venv",
  "venv",
  "__pycache__",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  ".tox",
  ".nox",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".turbo",
  ".cache",
  ".gradle",
  ".idea",
  ".vscode-test",
  "target",
  "coverage",
  ".nyc_output",
];

const TEST_PATTERNS: RegExp[] = [
  /(^|\/)(tests?|__tests__|spec|specs|e2e|integration_tests)\//,
  /\.(test|spec|e2e)\.[cm]?[jt]sx?$/,
  /(^|\/)test_[^/]+\.py$/,
  /_test\.(py|go)$/,
  /(^|\/)conftest\.py$/,
  /Tests?\.(java|kt|cs|swift)$/,
];

const FIXTURE_PATTERNS: RegExp[] = [
  /(^|\/)(fixtures?|__fixtures__|testdata|test-data|__snapshots__|__golden__|snapshots)\//,
  /\.snap$/,
];

const VENDORED_PATTERNS: RegExp[] = [/(^|\/)(vendor|third_party|third-party|external)\//];

const GENERATED_PATTERNS: RegExp[] = [
  /(^|\/)(dist|build|out|lib-cov|generated|__generated__)\//,
  /\.min\.(js|css)$/,
  /\.(map|d\.ts\.map)$/,
  /_pb2(_grpc)?\.py$/,
  /\.pb\.go$/,
  /\.generated\.[a-z]+$/,
  /(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|poetry\.lock|uv\.lock|Pipfile\.lock|Cargo\.lock|go\.sum|composer\.lock|Gemfile\.lock)$/,
];

const DOC_PATTERNS: RegExp[] = [/\.(md|mdx|rst|adoc|txt)$/i, /(^|\/)docs?\//];

const CONFIG_PATTERNS: RegExp[] = [
  /(^|\/)\.[^/]+rc(\.[a-z]+)?$/,
  /\.config\.[cm]?[jt]s$/,
  /(^|\/)(package\.json|tsconfig[^/]*\.json|pyproject\.toml|setup\.cfg|setup\.py|tox\.ini|Cargo\.toml|go\.mod|pom\.xml|build\.gradle(\.kts)?|Makefile|Dockerfile[^/]*|docker-compose[^/]*\.ya?ml|compose\.ya?ml)$/,
  /(^|\/)\.github\//,
  /(^|\/)\.gitlab-ci\.yml$/,
  /(^|\/)\.circleci\//,
  /\.(ya?ml|toml|ini|cfg)$/,
];

/** Order matters: a generated file under tests/ is still generated, not a test. */
export function classifyFile(path: string, language: string): FileRole {
  if (VENDORED_PATTERNS.some((re) => re.test(path))) return "vendored";
  if (GENERATED_PATTERNS.some((re) => re.test(path))) return "generated";
  if (FIXTURE_PATTERNS.some((re) => re.test(path))) return "fixture";
  if (TEST_PATTERNS.some((re) => re.test(path))) return "test";
  if (CONFIG_PATTERNS.some((re) => re.test(path))) return "config";
  if (isProgrammingLanguage(language)) return "source";
  if (DOC_PATTERNS.some((re) => re.test(path))) return "docs";
  if (language === "JSON" || language === "XML" || language === "Other") return "data";
  return "other";
}

/** Generated files are often valid code but are rarely written by a human. Checked on content. */
export function looksGenerated(head: string): boolean {
  return /@generated|auto-?generated|do not edit|generated by/i.test(head.slice(0, 600));
}
