import { describe, expect, it } from "vitest";
import { classifyFile, isSecretPath, looksGenerated } from "./classify.js";
import { detectLanguage } from "./languages.js";

const role = (p: string) => classifyFile(p, detectLanguage(p));

describe("isSecretPath", () => {
  it.each([".env", "config/.env.production", "certs/server.pem", "home/.ssh/id_rsa", ".npmrc"])(
    "treats %s as secret",
    (p) => expect(isSecretPath(p)).toBe(true),
  );

  it.each([".env.example", "src/env.ts", "docs/keys.md", "src/secretary.py"])("allows %s", (p) =>
    expect(isSecretPath(p)).toBe(false),
  );
});

describe("classifyFile", () => {
  it.each([
    ["src/server.ts", "source"],
    ["app/models.py", "source"],
    ["src/math.test.ts", "test"],
    ["tests/test_billing.py", "test"],
    ["pkg/handler_test.go", "test"],
    ["fixtures/js-app/src/index.ts", "fixture"],
    ["vendor/lib/x.js", "vendored"],
    ["dist/index.js", "generated"],
    ["pnpm-lock.yaml", "generated"],
    ["package.json", "config"],
    [".github/workflows/ci.yml", "config"],
    ["vite.config.ts", "config"],
    ["README.md", "docs"],
    ["data/users.json", "data"],
  ])("%s is %s", (p, expected) => expect(role(p)).toBe(expected));
});

describe("looksGenerated", () => {
  it("detects generator banners", () => {
    expect(looksGenerated("// Code generated by protoc. DO NOT EDIT.\n")).toBe(true);
    expect(looksGenerated("export const x = 1;\n")).toBe(false);
  });
});
