const BY_EXTENSION: Record<string, string> = {
  ts: "TypeScript",
  mts: "TypeScript",
  cts: "TypeScript",
  tsx: "TSX",
  js: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  jsx: "JavaScript",
  py: "Python",
  pyi: "Python",
  go: "Go",
  rs: "Rust",
  java: "Java",
  kt: "Kotlin",
  kts: "Kotlin",
  scala: "Scala",
  c: "C",
  h: "C",
  cc: "C++",
  cpp: "C++",
  cxx: "C++",
  hpp: "C++",
  hh: "C++",
  cs: "C#",
  fs: "F#",
  rb: "Ruby",
  php: "PHP",
  swift: "Swift",
  m: "Objective-C",
  mm: "Objective-C",
  dart: "Dart",
  lua: "Lua",
  r: "R",
  jl: "Julia",
  ex: "Elixir",
  exs: "Elixir",
  erl: "Erlang",
  hs: "Haskell",
  ml: "OCaml",
  clj: "Clojure",
  zig: "Zig",
  nim: "Nim",
  pl: "Perl",
  sh: "Shell",
  bash: "Shell",
  zsh: "Shell",
  ps1: "PowerShell",
  sql: "SQL",
  vue: "Vue",
  svelte: "Svelte",
  html: "HTML",
  htm: "HTML",
  css: "CSS",
  scss: "SCSS",
  sass: "SCSS",
  less: "Less",
  md: "Markdown",
  mdx: "Markdown",
  rst: "reStructuredText",
  txt: "Text",
  json: "JSON",
  jsonc: "JSON",
  yml: "YAML",
  yaml: "YAML",
  toml: "TOML",
  xml: "XML",
  ini: "INI",
  cfg: "INI",
  proto: "Protocol Buffers",
  graphql: "GraphQL",
  gql: "GraphQL",
  tf: "Terraform",
  hcl: "HCL",
  gradle: "Gradle",
  ipynb: "Jupyter Notebook",
};

const BY_FILENAME: Record<string, string> = {
  dockerfile: "Dockerfile",
  makefile: "Makefile",
  gnumakefile: "Makefile",
  jenkinsfile: "Groovy",
  gemfile: "Ruby",
  rakefile: "Ruby",
  justfile: "Just",
};

/** Languages that are code (counted in the language mix), as opposed to data or prose. */
const PROGRAMMING = new Set([
  "TypeScript",
  "TSX",
  "JavaScript",
  "Python",
  "Go",
  "Rust",
  "Java",
  "Kotlin",
  "Scala",
  "C",
  "C++",
  "C#",
  "F#",
  "Ruby",
  "PHP",
  "Swift",
  "Objective-C",
  "Dart",
  "Lua",
  "R",
  "Julia",
  "Elixir",
  "Erlang",
  "Haskell",
  "OCaml",
  "Clojure",
  "Zig",
  "Nim",
  "Perl",
  "Shell",
  "PowerShell",
  "SQL",
  "Vue",
  "Svelte",
  "Groovy",
]);

export function detectLanguage(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1).toLowerCase();
  const byName = BY_FILENAME[base];
  if (byName) return byName;
  if (base.startsWith("dockerfile")) return "Dockerfile";
  const dot = base.lastIndexOf(".");
  if (dot <= 0) return "Other";
  return BY_EXTENSION[base.slice(dot + 1)] ?? "Other";
}

export function isProgrammingLanguage(language: string): boolean {
  return PROGRAMMING.has(language);
}
